# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
        NOT_CRAN: true
        TZ: UTC
        R_LIBS_USER: tempdir/Library
        _R_CHECK_SYSTEM_CLOCK: FALSE
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        r-version: [3.5]


    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: JavaR  reconf
        run: sudo R CMD javareconf 
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
#
      - name: Set up Java
        uses: actions/setup-java@v1
        with: 
            java-version: 1.8
      - name: build with maven
        run:  mvn --batch-mode package

      - name: build R package
        run: cd ..; R CMD build SqlRender

      - name: mkdirs
        run: mkdir staging && cp ../SqlRender_1.6.8.tar.gz staging
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
      - name: upload release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
            upload_url: ${{ steps.create_release.outputs.upload.upload_url }}
            asset_path: ./SqlRender_1.6.8.tar.gz
            asset_name: SqlRender_1.6.8.tar.gz
            asset_content_type: application/zip
