# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
        NOT_CRAN: true
        TZ: UTC
        R_LIBS_USER: tempdir/Library
        _R_CHECK_SYSTEM_CLOCK: FALSE
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        r-version: [3.5]


    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
#      - name: Install dependencies
#        run: |
#          install.packages(c("remotes", "rcmdcheck"))
#          remotes::install_deps(dependencies = TRUE)
#        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
#
      - name: Set up Java
        uses: actions/setup-java@v1
        with: 
            java-version: 1.8
      - name: build with maven
        run:  mvn --batch-mode package
      - name: upload
        run: mkdir staging && cp target/*.jar staging
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
