
name: R

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: basic test 2
          run: Rscript -e 'print("basic test 2")'
